require('plugins_setup.lsp')
require('plugins_setup.lualine')
require('plugins_setup.fugitive')
require('plugins_setup.treesitter')
require('plugins_setup.undotree')
require('plugins_setup.telescope')
require('plugins_setup.colorscheme')
